config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
   resources :attachments

  root 'home#index'
  get '/' => 'home#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	dragonfly_accessor :image
	validates :title, presence: true
	validates :text, presence: true
	validates :image, presence: true
	
	
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	dragonfly_accessor :image
	validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  			before_filter :configure_permitted_parameters, if: :devise_controller?

	private

		def configure_permitted_parameters
		  devise_parameter_sanitizer.for(:sign_up) << :username       
  		   devise_parameter_sanitizer.for(:sign_in) << :username       
		 devise_parameter_sanitizer.for(:account_update) << :username  


		end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]	


	def destroy
		@article = Article.find(params[:id])
		if @article.author == current_user.username.capitalize 	
 		    @article.destroy
 		 	redirect_to '/'
 		else redirect_to @article
 		end
	end

	def update                            
		@article = Article.find(params[:id])
		if @article.author == current_user.username.capitalize 	
			if @article.update(article_params)
	 			redirect_to @article
			else
				render action: 'edit'
			end
		else redirect_to @article
		end
	end

	def show
		@article = Article.find(params[:id])
	
	end

	def edit
		@article = Article.find(params[:id])
	end

	def new
	end

	def create
		@article = Article.new(article_params)
		@article.author = current_user.username.capitalize
		if @article.valid?
				
			#	if @article.text.include? "src=" 
			 #       	@article.text.insert(@article.text.index('src='),'class="pickta" ')	
			  #      end
			  
			@article.save
			render action: 'show'
		else
			render action: 'new'
		end

	end

	private 
	def article_params
	params.require(:article).permit(:title, :text, :image, :original)

	end		
	

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)
  if @attachment.valid?
      
    # if @article.text.include? "src=" 
     #        @article.text.insert(@article.text.index('src='),'class="pickta" ') 
      #      end
      
    @attachment.save
    render action: 'show'
  else
    render action: 'new'
  end

  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@main_article = Article.last
	@small_articles = Article.last(4).reverse.slice(1..3)
	@last_articles = Article.last(16).reverse.slice(4..16)
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/create.html.erb
<h1>Article</h1>


<%= @article.inspect %>

app/views/articles/edit.html.erb
<div class='col-md-8'>
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<% if @article && @article.errors.any? %> 
   <p>  <ul>
	<% @article.errors.full_messages.each do|msg| %>
	<li><%= msg %></li>
	<% end %> </ul>
	</p>         
  <%end%>
   <p>
   <%= f.label :add_Photo %><br />
   <%= f.file_field :image, :multiple => true %>

   </p>
   <p>
   <%= f.label :title %><br />
   <%= f.text_field :title %>
   </p>
    <p>
 <%= f.label :text %><br />  
 <%= f.text_area :text, rows: 10, cols: 70 %>
   </p>

  <p>
 <%= f.label :original %><br />  
 <%= f.text_field :original, size: 70 %>
   </p>
   <%= f.submit 'Save'%>

<% end %>
</div>

<div class='col-md-4'>.
<% articles = Article.all %>
<% articles.each do |article| %>
        <% if article.image_uid? %>
        <% article1 = article.image.url%>
        <img onclick="hi('article_text','<%=article1%>')" height="30%" width="30%" src='<%= article.image.url %>'>
        <% end %>
<% end %>
</div>

app/views/articles/new.html.erb
<h1>News</h1>
<div class='col-md-8'>
<%= form_for :article, url: articles_path do |f| %>
	<% if @article && @article.errors.any? %> 
   <p>  <ul>
	<% @article.errors.full_messages.each do|msg| %>
	<li><%= msg %></li>
	<% end %> </ul>
	</p>         
  <%end%>
   <p>
   <%= f.label :add_Photo %><br />
   <%= f.file_field :image %>
   
   </p>
   <p>
   <%= f.label :title %><br />
   <%= f.text_field :title, size: 71 %>
   </p>
    <p>
 <%= f.label :text %><br />  
 <%= f.text_area :text, rows: 10, cols: 70 %>
   </p>

   <p>

 <%= f.label :original %> (УДАЛИ WWW. ИЗ АДРЕСА) <br />  
 <%= f.text_field :original, size: 70 %>
   </p>

   <%= f.submit 'Save'%>

<% end %>
</div>

<div class='col-md-4'>.
<% attachments = Attachment.all %>
<% attachments.each do |attachment| %>
        <% if attachment.image_uid? %>
        <% attachment1 = attachment.image.url%>
        <img onclick="hi('article_text','<%=attachment1%>')" height="30%" width="30%" src='<%= attachment.image.url %>'>
        <% end %>
<% end %>
</div>   

app/views/articles/show.html.erb
<div class='container'>
	
	
	<% if @article.image_uid?  %>
		<img style="max-width:100%;height:auto;" src='<%= @article.image.url %>'>
	<% else %>	
		<img align='top' height="100%" width="100%" src='../netcart.jpg'>
	<% end %>
</div>
<div class='container' style="margin:20px 0 20px;">
	<div class='news-font'>
	
		<h2 style="margin:0 20px;" ><%= @article.title %> </h2>
		<div style="margin:30px 20px;" ><%= @article.text.html_safe %></div>
		   	<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
			<script src="//yastatic.net/share2/share.js"></script>
			<div style="text-align:right;font-size:10pt"> Рассказать всему интернету
			<div class="ya-share2" 
				 data-services="vkontakte,facebook" 
				 data-title="<%= @article.title %>"
				 data-description="<%= @article.text[0,@article.text.index('.').to_i + 1] %>"
				 data-counter="">
				 
			</div>
			</div>

			<% if @article.original?%>
			<div style="text-align: center;">
			<a target="_blank" href="<%= @article.original %>" class="btn btn-default btn-lg active" 
			   role="button">Оригинальная статья взята с сайта <%= @article.original[7,@article.original.index('/',7).to_i - 7].capitalize%></a>
			<% end %>   
</div>
	</div>
</div>
	<% if user_signed_in? %>
		<%= link_to 'prosmotr', article_path(@article) %>
		<%= link_to 'edit', edit_article_path(@article)%>
		<%= link_to 'delete', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
	 <% end%>   

app/views/articles/update.html.erb
SAve

app/views/attachments/create.html.erb
create

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Image uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.reverse.each do |attachment| %>
      <tr>
        <td><img  height="auto" width="100" src='<%= attachment.image.url %>'></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<div class='col-md-8'>
<%= form_for :attachment, url: attachments_path do |f| %>

   <p>
   <%= f.label :add_Photo %><br />
   <%= f.file_field :image %>
   
 <br />

   <%= f.submit 'Save'%>

<% end %>
</div>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image uid:</strong>
  <%= @attachment.image_uid %>
</p>

app/views/home/index.html.erb
 <div class='container'>
 	

 <div class="row" >

 	<% if @main_article.image_stored?%>
		 <div class="col-md-8">
		 	<a href='<%= article_path(@main_article)%>'><img align='left' height="100%" width="100%" 
		 	<% if @main_article.image_uid?  %>
		 		src='<%= @main_article.image.url %>'></a>
		 	<% else %>	
				src='../netcart.jpg'></a>
			<% end %>

		 </div>
		 <div class="col-md-4">	
		 			<p><font size="6">Last news</font></p>	
		 			<% @last_articles.each do |article| %>
		 			<p><%= link_to truncate(article.title, length: 30), article_path(article) %></p>
					<%end%>
		</div>

	<% end %>      

</div>

 <div class="row" >

	<% @small_articles.each do |article|%>
 	
		<div class="col-md-4"> <a href='<%= article_path(article)%>'> <img align='top' vspace='10px' height="200" width="100%" 
		<% if article.image_uid?  %>
			src='<%= article.image.url %>'> 
		<% else %>	
			src='../netcart.jpg'>
		<% end %>
							<h4><%= article.title%></h4>
							<span><font size="2"><%= article.text[0,article.text.index('.').to_i + 1] %></font></span>
		</a></div>
	


<!--	<%= link_to 'prosmotr', article_path(article) %>
	<%= link_to 'edit', edit_article_path(article)%>
	<%= link_to 'delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
	=========================
	<br />
-->
   
	<% end %>
</div>
</div> </div>
<div class='leaderblock'>
  <div class='container'>
  <div style="color:#c0c0c0;margin:20px 0 0 0;text-align:center;font-size:30pt;">Таблица лидеров</div> 
	<div class="row">
  		<div class="col-xs-6 col-md-4 image_inpost" style="color:#FFC940;font-size:20pt;">1. Mett Wilkinson 
  		<img style="margin:20px 0;" src='http://fast1.onesite.com/capcom-unity.com/user/darkstalkers/dante_avatar.png'> 
 		<div style="font-size:20pt;"> Очки </div> 
 		<div style="font-size:40pt;"> 34000 </div>
 		</div>
	<div class="row">
  		<div class="col-xs-6 col-md-4 image_inpost" style="color:#c0c0c0;font-size:20pt;">1. Mett Wilkinson 
  		<img style="margin:20px 0;" src='http://fast1.onesite.com/capcom-unity.com/user/darkstalkers/dante_avatar.png'> 
 		<div style="font-size:20pt;"> Очки </div> 
 		<div style="font-size:40pt;"> 34000 </div>
 		</div>
	<div class="row">
  		<div class="col-xs-6 col-md-4 image_inpost" style="color:#c0c0c0;font-size:20pt;">1. Mett Wilkinson 
  		<img style="margin:20px 0;" src='http://fast1.onesite.com/capcom-unity.com/user/darkstalkers/dante_avatar.png'> 
 		<div style="font-size:20pt;"> Очки </div> 
 		<div style="font-size:40pt;"> 34000 </div>
 		</div>
	</div>
	</div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vslnarusskom</title>                                                              
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>                            
 



</head>
<body >                      

 <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container" >

      <a class="navbar-brand" href="/">Home</a>
       <% if user_signed_in? %>
       <a class="navbar-brand" href="/articles/new">New Article</a>
                      <a class="navbar-brand" href="/attachments/new">Add photo</a>
               <div class="navbar-right navbar-brand">
                                                                           
                  
                     
                       <%= current_user.username %>   <%= link_to 'Sign out!', destroy_user_session_path, method: :delete %>  </div>
                   <% else%>       
                   <div class="navbar-right navbar-brand">                                    
                     <%= link_to 'Sign in!', new_user_session_path %> </div>
                    <% end%>   
                 
                 
        </div>



    </div>

  </nav>
	<div style="margin-bottom:20px" class="container">
<%= yield %>
	</div>


 <nav class="navbar navbar-default ">
    <div class="container" >

      <a class="navbar-brand" href="/contact">Контакты</a>
      <a class="navbar-brand" href="/about">О нас</a>
      
     </div>

     <div class="container" >
        <p>(c) F Company 2016.  All rights reserved.</p>
     </div>
 </nav> 
</body>
</html>